"use client";

import { useMemo,useState } from "react";
import { useCooking } from "@/components/CookingProvider";
import { getKitchenAliases,getKitchenCategory,getKitchenDisplayName,getPurchaseChannelLabel,kitchenDictionary,searchKitchenDictionary,type KitchenEntryKind } from "@/lib/kitchen-dictionary";
import { useLocale } from "@/lib/i18n";
import type { IngredientMapping } from "@/lib/types";

type Scope="all"|KitchenEntryKind;

export default function IngredientsPage(){
  const {ingredients,saveIngredient}=useCooking();const {locale,t}=useLocale();const [query,setQuery]=useState("");const [scope,setScope]=useState<Scope>("all");const [editing,setEditing]=useState<IngredientMapping|null>(null);
  const builtIn=useMemo(()=>searchKitchenDictionary(query,scope),[query,scope]);
  const personal=useMemo(()=>ingredients.filter(i=>[i.zh,i.zhTW||"",i.en,i.de,i.germanHint].join(" ").toLowerCase().includes(query.toLowerCase())),[ingredients,query]);
  const save=(e:React.FormEvent)=>{e.preventDefault();if(editing){saveIngredient(editing);setEditing(null)}};
  const ingredientCount=kitchenDictionary.filter(i=>i.kind==="ingredient").length;const toolCount=kitchenDictionary.filter(i=>i.kind==="tool").length;
  return <div className="page">
    <header className="page-head"><div><p className="eyebrow">{t("dictionary.eyebrow")}</p><h1>{t("dictionary.title")}</h1><p className="subtitle">{t("dictionary.subtitle")}</p></div><button className="btn btn-primary" onClick={()=>setEditing({id:crypto.randomUUID(),zh:"",zhTW:"",en:"",de:"",category:"其他",germanHint:"",gluten:"需核验",verified:false})}>{t("dictionary.addPersonal")}</button></header>
    <div className="stats" style={{gridTemplateColumns:"repeat(3,1fr)",marginBottom:18}}><div className="stat"><div className="stat-label">{t("dictionary.builtInIngredients")}</div><div className="stat-value">{ingredientCount}</div></div><div className="stat"><div className="stat-label">{t("dictionary.builtInTools")}</div><div className="stat-value">{toolCount}</div></div><div className="stat"><div className="stat-label">{t("dictionary.myEntries")}</div><div className="stat-value">{ingredients.length}</div></div></div>
    <div className="search-panel"><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{(["all","ingredient","tool"] as Scope[]).map(key=><button key={key} className={`btn ${scope===key?"btn-primary":"btn-secondary"}`} onClick={()=>setScope(key)}>{key==="all"?t("dictionary.all"):key==="ingredient"?t("dictionary.ingredient"):t("dictionary.tool")}</button>)}</div><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("dictionary.search")}/></div>
    <div className="table-wrap"><table><thead><tr><th>{t("dictionary.names")}</th><th>{t("dictionary.english")}</th><th>{t("dictionary.german")}</th><th>{t("dictionary.category")}</th><th>{t("dictionary.purchase")}</th></tr></thead><tbody>{builtIn.map(item=>{const aliases=getKitchenAliases(item,locale);return <tr key={item.id}><td><b>{getKitchenDisplayName(item,locale)}</b>{aliases.length>0&&<><br/><small>{aliases.join("、")}</small></>}</td><td>{item.en}</td><td>{item.de}</td><td><span className="badge">{item.kind==="ingredient"?t("dictionary.ingredient"):t("dictionary.tool")}</span><br/><small>{getKitchenCategory(item,locale)}</small></td><td>{item.kind==="ingredient"?<><b>{getPurchaseChannelLabel(item.channel,locale)}</b>{item.shelfHint&&<><br/><small>{item.shelfHint}</small></>}</>:<span className="subtitle">{t("dictionary.kitchenTool")}</span>}{item.note&&<><br/><small>{item.note}</small></>}</td></tr>})}</tbody></table></div>
    {!builtIn.length&&<div className="panel empty" style={{marginTop:14}}>{t("dictionary.empty")}</div>}

    <div className="section-head" style={{marginTop:24}}><div><p className="eyebrow">{t("dictionary.personalEyebrow")}</p><h2>{t("dictionary.personalTitle")}</h2></div><span className="subtitle">{t("dictionary.personalSubtitle")}</span></div>
    {personal.length?<div className="table-wrap"><table><thead><tr><th>{t("dictionary.names")}</th><th>{t("dictionary.english")}</th><th>{t("dictionary.german")}</th><th>{t("dictionary.germanHint")}</th><th>{t("dictionary.verification")}</th></tr></thead><tbody>{personal.map(i=><tr key={i.id} onClick={()=>setEditing(i)} style={{cursor:"pointer"}}><td><b>{locale==="zh-TW"&&i.zhTW?.trim()?i.zhTW:i.zh}</b>{i.zhTW?.trim()&&i.zhTW!==i.zh&&<><br/><small>{locale==="zh-TW"?i.zh:i.zhTW}</small></>}<br/><small>{i.category}</small></td><td>{i.en}</td><td>{i.de}</td><td>{i.germanHint}</td><td><span className={`badge ${i.verified?"":"muted"}`}>{i.verified?t("dictionary.confirmed"):t("dictionary.pending")}</span></td></tr>)}</tbody></table></div>:<div className="notice">{t("dictionary.personalEmpty")}</div>}
    {editing&&<div className="panel" style={{marginTop:18}}><div className="section-head"><h2>{ingredients.some(i=>i.id===editing.id)?t("dictionary.editTitle"):t("dictionary.addTitle")}</h2><button className="icon-btn" onClick={()=>setEditing(null)}>×</button></div><form onSubmit={save} className="form-grid"><div className="field"><label>{t("dictionary.zhCN")}</label><input required value={editing.zh} onChange={e=>setEditing({...editing,zh:e.target.value})}/></div><div className="field"><label>{t("dictionary.zhTW")}</label><input value={editing.zhTW||""} onChange={e=>setEditing({...editing,zhTW:e.target.value})}/></div><div className="field"><label>{t("dictionary.category")}</label><input value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}/></div><div className="field"><label>{t("dictionary.english")}</label><input value={editing.en} onChange={e=>setEditing({...editing,en:e.target.value})}/></div><div className="field"><label>{t("dictionary.german")}</label><input value={editing.de} onChange={e=>setEditing({...editing,de:e.target.value})}/></div><div className="field full"><label>{t("dictionary.germanHint")}</label><textarea value={editing.germanHint} onChange={e=>setEditing({...editing,germanHint:e.target.value})}/></div><div className="field"><label>{t("dictionary.gluten")}</label><select value={editing.gluten} onChange={e=>setEditing({...editing,gluten:e.target.value as IngredientMapping["gluten"]})}><option value="需核验">{t("dictionary.pending")}</option><option value="否">否 / No</option><option value="是">是 / Yes</option></select></div><div className="field"><label>{t("dictionary.verification")}</label><select value={editing.verified?"yes":"no"} onChange={e=>setEditing({...editing,verified:e.target.value==="yes"})}><option value="no">{t("dictionary.pending")}</option><option value="yes">{t("dictionary.confirmed")}</option></select></div><div className="field full"><button className="btn btn-primary" type="submit">{t("dictionary.save")}</button></div></form></div>}
    <div className="notice" style={{marginTop:16}}>{t("dictionary.safety")}</div>
  </div>;
}
