"use client";

import { useMemo,useState } from "react";
import { useCooking } from "@/components/CookingProvider";
import { kitchenDictionary,purchaseChannelLabels,searchKitchenDictionary,type KitchenEntryKind } from "@/lib/kitchen-dictionary";
import type { IngredientMapping } from "@/lib/types";

type Scope="all"|KitchenEntryKind;

export default function IngredientsPage(){
  const {ingredients,saveIngredient}=useCooking();const [query,setQuery]=useState("");const [scope,setScope]=useState<Scope>("all");const [editing,setEditing]=useState<IngredientMapping|null>(null);
  const builtIn=useMemo(()=>searchKitchenDictionary(query,scope),[query,scope]);
  const personal=useMemo(()=>ingredients.filter(i=>[i.zh,i.en,i.de,i.germanHint].join(" ").toLowerCase().includes(query.toLowerCase())),[ingredients,query]);
  const save=(e:React.FormEvent)=>{e.preventDefault();if(editing){saveIngredient(editing);setEditing(null)}};
  const ingredientCount=kitchenDictionary.filter(i=>i.kind==="ingredient").length;const toolCount=kitchenDictionary.filter(i=>i.kind==="tool").length;
  return <div className="page">
    <header className="page-head"><div><p className="eyebrow">KITCHEN DICTIONARY</p><h1>厨房词典</h1><p className="subtitle">把食材、地区叫法和厨具统一成中文 / English / Deutsch。采购页面只负责购物，不再重复维护翻译。</p></div><button className="btn btn-primary" onClick={()=>setEditing({id:crypto.randomUUID(),zh:"",en:"",de:"",category:"其他",germanHint:"",gluten:"需核验",verified:false})}>＋ 补充个人食材</button></header>
    <div className="stats" style={{gridTemplateColumns:"repeat(3,1fr)",marginBottom:18}}><div className="stat"><div className="stat-label">内置食材</div><div className="stat-value">{ingredientCount}</div></div><div className="stat"><div className="stat-label">内置厨具</div><div className="stat-value">{toolCount}</div></div><div className="stat"><div className="stat-label">我的补充</div><div className="stat-value">{ingredients.length}</div></div></div>
    <div className="search-panel"><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{(["all","ingredient","tool"] as Scope[]).map(key=><button key={key} className={`btn ${scope===key?"btn-primary":"btn-secondary"}`} onClick={()=>setScope(key)}>{key==="all"?"全部":key==="ingredient"?"食材":"厨具"}</button>)}</div><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜：土豆 / 洋芋 / potato / Kartoffel / 捣蒜锤…"/></div>
    <div className="table-wrap"><table><thead><tr><th>中文与别名</th><th>English</th><th>Deutsch</th><th>分类</th><th>采购 / 说明</th></tr></thead><tbody>{builtIn.map(item=><tr key={item.id}><td><b>{item.zh}</b>{item.aliases.length>0&&<><br/><small>{item.aliases.join("、")}</small></>}</td><td>{item.en}</td><td>{item.de}</td><td><span className="badge">{item.kind==="ingredient"?"食材":"厨具"}</span><br/><small>{item.category}</small></td><td>{item.kind==="ingredient"?<><b>{purchaseChannelLabels[item.channel]}</b>{item.shelfHint&&<><br/><small>{item.shelfHint}</small></>}</>:<span className="subtitle">厨房工具</span>}{item.note&&<><br/><small>{item.note}</small></>}</td></tr>)}</tbody></table></div>
    {!builtIn.length&&<div className="panel empty" style={{marginTop:14}}>内置词典里暂时没有这个词，可以在下面补充个人食材；厨具缺词后续继续扩充。</div>}

    <div className="section-head" style={{marginTop:24}}><div><p className="eyebrow">MY OVERRIDES</p><h2>我的食材补充</h2></div><span className="subtitle">用于记录你实际在德国看到的包装名称、地区叫法和购买经验</span></div>
    {personal.length?<div className="table-wrap"><table><thead><tr><th>中文</th><th>English</th><th>Deutsch</th><th>个人购买提示</th><th>校验</th></tr></thead><tbody>{personal.map(i=><tr key={i.id} onClick={()=>setEditing(i)} style={{cursor:"pointer"}}><td><b>{i.zh}</b><br/><small>{i.category}</small></td><td>{i.en}</td><td>{i.de}</td><td>{i.germanHint}</td><td><span className={`badge ${i.verified?"":"muted"}`}>{i.verified?"已确认":"待确认"}</span></td></tr>)}</tbody></table></div>:<div className="notice">还没有个人补充。内置词典会直接用于采购清单匹配；遇到地区差异时再把自己的版本补在这里。</div>}
    {editing&&<div className="panel" style={{marginTop:18}}><div className="section-head"><h2>{ingredients.some(i=>i.id===editing.id)?"编辑个人食材":"补充个人食材"}</h2><button className="icon-btn" onClick={()=>setEditing(null)}>×</button></div><form onSubmit={save} className="form-grid"><div className="field"><label>中文名 *</label><input required value={editing.zh} onChange={e=>setEditing({...editing,zh:e.target.value})}/></div><div className="field"><label>分类</label><input value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}/></div><div className="field"><label>英文名</label><input value={editing.en} onChange={e=>setEditing({...editing,en:e.target.value})}/></div><div className="field"><label>德文名</label><input value={editing.de} onChange={e=>setEditing({...editing,de:e.target.value})}/></div><div className="field full"><label>德国购买提示</label><textarea value={editing.germanHint} onChange={e=>setEditing({...editing,germanHint:e.target.value})}/></div><div className="field"><label>无麸质状态</label><select value={editing.gluten} onChange={e=>setEditing({...editing,gluten:e.target.value as IngredientMapping["gluten"]})}><option>需核验</option><option>否</option><option>是</option></select></div><div className="field"><label>人工校验</label><select value={editing.verified?"yes":"no"} onChange={e=>setEditing({...editing,verified:e.target.value==="yes"})}><option value="no">待确认</option><option value="yes">已确认</option></select></div><div className="field full"><button className="btn btn-primary" type="submit">保存个人映射</button></div></form></div>}
    <div className="notice" style={{marginTop:16}}>词典里的超市位置用于采购导航，不代表某一家门店实时有货。过敏原与无麸质结论仍以具体包装为准。</div>
  </div>;
}
