"use client";

import { useMemo, useState } from "react";
import { prepareBilibiliImport, type PreparedBilibiliImport } from "@/lib/bilibili";
import { useCooking } from "@/components/CookingProvider";
import type { ImportResult } from "@/lib/types";

export default function ImportsPage(){
  const {recipes,importJobs,importVideos,isDemo}=useCooking();
  const [prepared,setPrepared]=useState<PreparedBilibiliImport|null>(null);const [scope,setScope]=useState<"ten"|"all">("ten");const [error,setError]=useState("");const [result,setResult]=useState<ImportResult|null>(null);const [busy,setBusy]=useState(false);
  const existing=useMemo(()=>new Set(recipes.map(r=>r.source?.bvid).filter(Boolean)),[recipes]);
  const selectedVideos=prepared?.videos.slice(0,scope==="ten"?10:undefined)||[];const duplicates=selectedVideos.filter(v=>existing.has(v.bvid)).length;
  const pick=async(file?:File)=>{if(!file)return;setError("");setResult(null);try{setPrepared(prepareBilibiliImport(JSON.parse(await file.text()),file.name));}catch(e){setPrepared(null);setError(e instanceof Error?e.message:"JSON 读取失败");}};
  const confirm=async()=>{if(!prepared)return;setBusy(true);setError("");try{setResult(await importVideos(selectedVideos,{collectionId:prepared.collectionId,fileName:prepared.fileName,skipped:scope==="all"?prepared.skipped.length:0}));}catch(e){setError(e instanceof Error?e.message:"导入失败");}finally{setBusy(false);}};
  return <div className="page"><header className="page-head"><div><p className="eyebrow">BILIBILI IMPORT</p><h1>导入中心</h1><p className="subtitle">每次导入都会记录任务、逐条状态和原始元数据，方便查重、追错与重试。</p></div></header><div className="two-col"><section className="panel"><h2>1. 选择导出文件</h2><div className="dropzone"><div style={{fontSize:44}}>⇩</div><b>选择“做饭-日期.json”</b><p className="subtitle">文件只含公开视频元数据，不含 Cookie 或视频文件</p><input type="file" accept="application/json,.json" onChange={e=>pick(e.target.files?.[0])}/></div>{error&&<div className="notice" style={{marginTop:14,background:"#fbe5de",color:"#923c29"}}>读取失败：{error}</div>}
      {prepared&&<><div className="section-head"><h2>2. 导入预览</h2><span className="badge">{prepared.fileName}</span></div><div className="field" style={{marginBottom:16}}><label>本次导入范围</label><select value={scope} onChange={e=>setScope(e.target.value as "ten"|"all")}><option value="ten">先试导入前 10 条（推荐）</option><option value="all">导入全部 {prepared.videos.length} 条</option></select></div><div className="stats" style={{gridTemplateColumns:"repeat(4,1fr)",marginBottom:18}}><div className="stat"><div className="stat-label">本次处理</div><div className="stat-value">{selectedVideos.length}</div></div><div className="stat"><div className="stat-label">预计新增</div><div className="stat-value">{selectedVideos.length-duplicates}</div></div><div className="stat"><div className="stat-label">重复</div><div className="stat-value">{duplicates}</div></div><div className="stat"><div className="stat-label">全文件无效</div><div className="stat-value">{prepared.skipped.length}</div></div></div><div className="table-wrap"><table><thead><tr><th>标题</th><th>BV号</th><th>UP主</th><th>可提取字段</th><th>状态</th></tr></thead><tbody>{selectedVideos.slice(0,12).map(video=><tr key={video.bvid}><td>{video.title}</td><td>{video.bvid}</td><td>{video.uploader||"—"}</td><td>{[video.durationSeconds?"时长":"",video.publishedAt?"发布时间":"",video.description&&video.description!=="-"?"简介":""].filter(Boolean).join("、")||"仅基础信息"}</td><td><span className={`badge ${existing.has(video.bvid)?"muted":""}`}>{existing.has(video.bvid)?"重复":"可导入"}</span></td></tr>)}</tbody></table></div>{selectedVideos.length>12&&<p className="subtitle" style={{marginTop:10}}>当前只预览前 12 条，确认后会处理本次选择的 {selectedVideos.length} 条。</p>}<div className="notice" style={{marginTop:14}}>JSON 不含可靠的配料克数、火候或完整步骤；这些字段会保持为空，不能根据标题自动猜测。</div><button className="btn btn-primary" style={{marginTop:17}} onClick={confirm} disabled={busy}>{busy?"正在写入审计记录…":`确认导入 ${selectedVideos.length} 条`}</button></>}
      {result&&<div className="notice" style={{marginTop:14,background:"var(--leaf-soft)",color:"var(--leaf)"}}><b>{result.mode==="cloud"?"云端":"本机演示"}导入完成</b><br/>任务 {result.jobId.slice(0,8)}：新增 {result.added}，重复 {result.duplicates}，失败 {result.failed}，跳过 {result.skipped}。</div>}
    </section><aside><div className="panel"><h2>导入审计记录</h2><p className="subtitle">{isDemo?"当前未登录，记录只保存在本次浏览器状态中。":"已登录，记录来自 Supabase。"}</p>{importJobs.length?<div className="source-list">{importJobs.slice(0,8).map(job=><div key={job.id} style={{padding:"12px 0",borderBottom:"1px solid var(--line)"}}><b>{job.fileName||"B站收藏夹导入"}</b><small style={{display:"block",marginTop:4}}>{new Date(job.createdAt).toLocaleString("zh-CN")} · 新增 {job.added} / 重复 {job.duplicates} / 失败 {job.failed} / 跳过 {job.skipped}</small></div>)}</div>:<p className="subtitle">还没有导入任务。</p>}<div className="notice" style={{marginTop:16}}>三层记录：<br/>① import_jobs 记录整批结果；<br/>② import_items 记录每条状态；<br/>③ source_videos 保存规范化来源和原始元数据。</div></div></aside></div></div>;
}
