create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

create type recipe_status as enum ('inbox','to_try','successful','needs_work','favorite','archived');
create type recipe_visibility as enum ('private','public','link');
create type version_type as enum ('source_extracted','personal_current','snapshot');
create type verification_status as enum ('unverified','ai_suggested','user_verified','source_verified');

create table profiles(id uuid primary key references auth.users on delete cascade,display_name text,locale text not null default 'zh-CN',timezone text not null default 'Asia/Tokyo',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table source_videos(id uuid primary key default gen_random_uuid(),owner_id uuid not null references profiles on delete cascade,platform text not null default 'bilibili',external_id text not null,url text not null,title text not null,uploader_name text,cover_url text,description text,published_at timestamptz,availability text not null default 'available',raw_metadata jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(owner_id,platform,external_id));
create table import_jobs(id uuid primary key default gen_random_uuid(),owner_id uuid not null references profiles on delete cascade,source text not null,status text not null default 'pending',total_count int not null default 0,success_count int not null default 0,duplicate_count int not null default 0,failed_count int not null default 0,started_at timestamptz,finished_at timestamptz,created_at timestamptz not null default now());
create table import_items(id uuid primary key default gen_random_uuid(),job_id uuid not null references import_jobs on delete cascade,external_id text not null,status text not null,error_code text,raw_metadata jsonb,created_at timestamptz not null default now(),unique(job_id,external_id));
create table recipes(id uuid primary key default gen_random_uuid(),owner_id uuid not null references profiles on delete cascade,source_video_id uuid references source_videos on delete set null,title text not null,summary text not null default '',servings numeric not null default 2 check(servings>0),total_minutes int check(total_minutes>=0),difficulty text not null default 'easy',status recipe_status not null default 'inbox',visibility recipe_visibility not null default 'private',current_version_id uuid,cover_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table recipe_versions(id uuid primary key default gen_random_uuid(),recipe_id uuid not null references recipes on delete cascade,version_no int not null check(version_no>0),version_type version_type not null,change_note text,created_by uuid not null references profiles,created_at timestamptz not null default now(),unique(recipe_id,version_no));
alter table recipes add constraint recipes_current_version_fk foreign key(current_version_id) references recipe_versions(id) on delete set null;
create table ingredients(id uuid primary key default gen_random_uuid(),owner_id uuid references profiles on delete cascade,canonical_name_zh text not null,name_en text,name_de text,aliases text[] not null default '{}',category text,gluten_status text,allergen_notes text,verification_status verification_status not null default 'unverified',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table recipe_ingredients(id uuid primary key default gen_random_uuid(),version_id uuid not null references recipe_versions on delete cascade,ingredient_id uuid references ingredients on delete set null,display_name text not null,amount numeric check(amount>=0),unit text,preparation text,optional boolean not null default false,group_name text,sort_order int not null default 0);
create table tools(id uuid primary key default gen_random_uuid(),name_zh text not null unique,name_en text,name_de text,aliases text[] not null default '{}');
create table recipe_tools(version_id uuid not null references recipe_versions on delete cascade,tool_id uuid not null references tools on delete restrict,optional boolean not null default false,note text,primary key(version_id,tool_id));
create table steps(id uuid primary key default gen_random_uuid(),version_id uuid not null references recipe_versions on delete cascade,step_no int not null check(step_no>0),instruction text not null,duration_minutes int check(duration_minutes>=0),temperature_c numeric,tips text,unique(version_id,step_no));
create table tags(id uuid primary key default gen_random_uuid(),owner_id uuid references profiles on delete cascade,group_name text not null,slug text not null,name text not null,description text,unique(owner_id,slug));
create table recipe_tags(recipe_id uuid not null references recipes on delete cascade,tag_id uuid not null references tags on delete cascade,source text not null default 'user',confidence numeric check(confidence between 0 and 1),confirmed boolean not null default true,primary key(recipe_id,tag_id));
create table substitutions(id uuid primary key default gen_random_uuid(),ingredient_id uuid not null references ingredients on delete cascade,substitute_id uuid not null references ingredients on delete cascade,market text,ratio_text text,store_hint text,note text,verification_status verification_status not null default 'unverified');
create table cooking_logs(id uuid primary key default gen_random_uuid(),owner_id uuid not null references profiles on delete cascade,recipe_id uuid not null references recipes on delete cascade,cooked_at date not null default current_date,rating int check(rating between 1 and 5),result_status text,changes text,lessons text,next_time text,private boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table media(id uuid primary key default gen_random_uuid(),owner_id uuid not null references profiles on delete cascade,recipe_id uuid references recipes on delete cascade,cooking_log_id uuid references cooking_logs on delete cascade,storage_path text not null,media_type text not null default 'image',caption text,sort_order int not null default 0,created_at timestamptz not null default now());
create table share_links(id uuid primary key default gen_random_uuid(),owner_id uuid not null references profiles on delete cascade,recipe_id uuid not null references recipes on delete cascade,token_hash text not null unique,expires_at timestamptz,active boolean not null default true,created_at timestamptz not null default now());

create index recipes_owner_status_idx on recipes(owner_id,status,updated_at desc);create index source_external_idx on source_videos(platform,external_id);create index recipe_title_trgm_idx on recipes using gin(title gin_trgm_ops);create index ingredients_zh_trgm_idx on ingredients using gin(canonical_name_zh gin_trgm_ops);

alter table profiles enable row level security;alter table source_videos enable row level security;alter table import_jobs enable row level security;alter table import_items enable row level security;alter table recipes enable row level security;alter table recipe_versions enable row level security;alter table ingredients enable row level security;alter table recipe_ingredients enable row level security;alter table cooking_logs enable row level security;alter table media enable row level security;alter table share_links enable row level security;
create policy "own profile" on profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy "own sources" on source_videos for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "own import jobs" on import_jobs for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "own import items" on import_items for all using(exists(select 1 from import_jobs j where j.id=job_id and j.owner_id=auth.uid())) with check(exists(select 1 from import_jobs j where j.id=job_id and j.owner_id=auth.uid()));
create policy "own or public recipes" on recipes for select using(owner_id=auth.uid() or (visibility='public' and deleted_at is null));create policy "own recipe writes" on recipes for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "visible recipe versions" on recipe_versions for select using(exists(select 1 from recipes r where r.id=recipe_id and (r.owner_id=auth.uid() or r.visibility='public')));create policy "own recipe version writes" on recipe_versions for all using(exists(select 1 from recipes r where r.id=recipe_id and r.owner_id=auth.uid())) with check(exists(select 1 from recipes r where r.id=recipe_id and r.owner_id=auth.uid()));
create policy "read shared ingredients" on ingredients for select using(owner_id is null or owner_id=auth.uid());create policy "own ingredients" on ingredients for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "visible recipe ingredients" on recipe_ingredients for select using(exists(select 1 from recipe_versions v join recipes r on r.id=v.recipe_id where v.id=version_id and (r.owner_id=auth.uid() or r.visibility='public')));create policy "own recipe ingredient writes" on recipe_ingredients for all using(exists(select 1 from recipe_versions v join recipes r on r.id=v.recipe_id where v.id=version_id and r.owner_id=auth.uid())) with check(exists(select 1 from recipe_versions v join recipes r on r.id=v.recipe_id where v.id=version_id and r.owner_id=auth.uid()));
create policy "private logs" on cooking_logs for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());create policy "own media" on media for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());create policy "own shares" on share_links for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());

create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1)));return new;end;$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
