"use client";

import { useParams } from "next/navigation";
import Link from "next/link";
import { useCooking } from "@/components/CookingProvider";
import { SharePanel } from "@/components/SharePanel";
import { SubpageBack } from "@/components/SubpageBack";

const label={inbox:"待整理",to_try:"待尝试",successful:"已成功",needs_work:"需改进",favorite:"常做"};

export default function RecipeDetailPage(){
  const {id}=useParams<{id:string}>(); const {recipes,logs,deleteRecipe}=useCooking(); const recipe=recipes.find(r=>r.id===id); const recipeLogs=logs.filter(l=>l.recipeId===id);
  if(!recipe)return <div className="page"><header className="page-head"><div><p className="eyebrow">RECIPE DETAIL</p><h1>菜谱详情</h1><p className="subtitle">当前链接对应的菜谱可能已经删除，或者还没有同步到这个环境。</p></div></header><SubpageBack href="/recipes" label="返回菜谱库"/><div className="panel empty"><span>🍽️</span>没有找到这道菜。<br/><Link className="btn btn-secondary" href="/recipes" style={{marginTop:16}}>返回菜谱库</Link></div></div>;
  return <div className="page"><header className="page-head"><div><p className="eyebrow">{label[recipe.status]} · {recipe.visibility==="public"?"公开":"私密"}</p><h1>{recipe.title}</h1><p className="subtitle">{recipe.summary}</p></div><div style={{display:"flex",gap:9,flexWrap:"wrap"}}><Link className="btn btn-primary" href={`/recipes/${id}/cook`}>开始做菜</Link><Link className="btn btn-secondary" href={`/recipes/${id}/edit`}>编辑</Link></div></header><SubpageBack href="/recipes" label="返回菜谱库"/>
    <div className="two-col"><section><div className="detail-cover" style={{background:recipe.color}}>{recipe.emoji}</div><div className="panel" style={{marginTop:18}}><div className="section-head"><h2>我的当前版本</h2><span className="badge">{recipe.updatedAt} 更新</span></div><p className="subtitle">{recipe.versionNote||"尚未填写版本说明。"}</p><div className="meta-row" style={{fontSize:13,marginTop:18}}><span>◷ {recipe.totalMinutes||"?"} 分钟</span><span>♙ {recipe.servings} 人份</span><span>◇ {recipe.difficulty}</span></div><div className="tag-row">{recipe.tags.map(t=><span className="tag" key={t}>{t}</span>)}</div></div>
      <div className="panel" style={{marginTop:18}}><h2>步骤</h2><ol className="step-list">{recipe.steps.length?recipe.steps.map((step,index)=><li className="step-item" key={step.id}><span className="step-no">{index+1}</span><div><p>{step.instruction}</p>{step.minutes&&<small>约 {step.minutes} 分钟</small>}{step.tip&&<div className="notice" style={{marginTop:8}}>{step.tip}</div>}</div></li>):<p className="subtitle">步骤尚待从视频中整理。</p>}</ol></div>
      <div className="panel" style={{marginTop:18}}><div className="section-head"><h2>最近制作记录</h2><Link href={`/logs?recipe=${id}`}>添加记录 →</Link></div>{recipeLogs.length?<ul className="log-list">{recipeLogs.map(log=><li key={log.id}><b>{log.cookedAt} · {"★".repeat(log.rating)}</b><p className="subtitle">{log.notes}</p></li>)}</ul>:<p className="subtitle">还没有制作记录。做完以后把调整和结果记下来。</p>}</div>
    </section><aside><div className="panel"><h2>食材 · {recipe.servings} 人份</h2><ul className="ingredient-list">{recipe.ingredients.length?recipe.ingredients.map(item=><li key={item.id}><span>{item.name}<br/><small>{item.preparation}</small></span><b>{item.amount} {item.unit}</b></li>):<li><span>食材尚待整理</span></li>}</ul></div>{recipe.source&&<div className="panel" style={{marginTop:18}}><p className="eyebrow">SOURCE VIDEO</p><h2>原视频</h2><p className="subtitle">{recipe.source.title}</p><p className="subtitle">{recipe.source.uploader} · {recipe.source.bvid}</p><a href={recipe.source.url} target="_blank" rel="noreferrer" className="btn btn-secondary" style={{marginTop:12}}>打开 B 站来源 ↗</a></div>}<SharePanel recipeId={recipe.id} isPublic={recipe.visibility==="public"}/><div className="panel" style={{marginTop:18}}><h2>管理</h2><Link className="btn btn-secondary" style={{width:"100%"}} href={`/share/${recipe.id}`}>查看公开分享页</Link><button className="btn btn-danger" style={{width:"100%",marginTop:9}} onClick={()=>{if(confirm("确定删除这道菜和它的本地日志吗？")){deleteRecipe(recipe.id);window.location.assign("/recipes")}}}>删除菜谱</button></div></aside></div>
  </div>;
}
